---
- name: Install Filebeat
  hosts: Web
  become: true
  tasks:
  - name: Download filebeat .deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb

  - name: Install filebeat .deb
    command: dpkg -i filebeat-7.6.1-amd64.deb

  - name: Drop in filebeat.yml
    copy:
      src: /etc/ansible/filebeat_config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: Enable and Configure The System Module
    command: filebeat modules enable system

  - name: filebeat setup
    command: filebeat setup

  - name: Start filebeat
    command: service filebeat start