---
-  name: Install Metricbeat
   hosts: Web
   become: true
   tasks:
   - name: Download metricbeat .deb
     command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

   - name: Install metricbeat .deb
     command: dpkg -i metricbeat-7.6.1-amd64.deb

   - name: Drop in metricbeat.yml
     copy:
       src: /etc/ansible/metricbeat_config.yml
       dest: /etc/metricbeat/metricbeat.yml

   - name: Enable and Configure The System Module
     command: metricbeat modules enable system

   - name: metricbeat setup
     command: metricbeat setup

   - name: Start metricbeat
     command: systemctl start metricbeat